services:
  kuba-gra:
    image: rayzki/kuba-gra:2.0
    container_name: gry
    restart: unless-stopped
    ports:
      - "44611:80"
    depends_on:
      - backend

  backend:
    image: rayzki/kuba-gra-backend:2.0
    container_name: backend
    restart: unless-stopped
    volumes:
      - backend-data:/app/data
    expose:
      - "3001"

volumes:
  backend-data:
