services:
  kuba-gra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gry
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: unless-stopped
    volumes:
      - backend-data:/app/data
    expose:
      - "3001"

volumes:
  backend-data:
